export default [
  "Chair Dimension",
  "Cromulon Dimension",
  "Cronenberg Dimension",
  "Dimension 5-126",
  "Dimension C-137",
  "Dimension C-35",
  "Dimension C-500A",
  "Dimension D-99",
  "Dimension D716",
  "Dimension D716-B",
  "Dimension D716-C",
  "Dimension J-22",
  "Dimension J19ζ7",
  "Dimension K-22",
  "Dimension K-83",
  "Eric Stoltz Mask Dimension",
  "Evil Rick's Target Dimension",
  "Fantasy Dimension",
  "Fascist Dimension",
  "Fascist Shrimp Dimension",
  "Fascist Teddy Bear Dimension",
  "Giant Telepathic Spiders Dimension",
  "Magic Dimension",
  "Merged Dimension",
  "Phone Dimension",
  "Pizza Dimension",
  "Post-Apocalyptic Dimension",
  "Replacement Dimension",
  "Testicle Monster Dimension",
  "Tusk Dimension",
  "Unknown dimension",
  "Wasp Dimension",
  "unknown",
];
