export default [
  "Acid Plant",
  "Arcade",
  "Artificially generated world",
  "Asteroid",
  "Base",
  "Box",
  "Cluster",
  "Convention",
  "Customs",
  "Daycare",
  "Death Star",
  "Diegesis",
  "Dimension",
  "Dream",
  "Dwarf planet (Celestial Dwarf)",
  "Fantasy town",
  "Game",
  "Liquid",
  "Machine",
  "Menagerie",
  "Microverse",
  "Miniverse",
  "Mount",
  "Nightmare",
  "Non-Diegetic Alternative Reality",
  "Planet",
  "Quadrant",
  "Quasar",
  "Reality",
  "Resort",
  "Spa",
  "Space station",
  "Spacecraft",
  "TV",
  "Teenyverse",
  "Woods",
  "unknown",
];
